[package]
name = "linked_list_allocator"
version = "0.2.2"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "Apache-2.0/MIT"

description = "Simple allocator usable for no_std systems. It builds a linked list from the freed blocks and thus needs no additional data structures."
keywords = ["allocator", "no_std", "malloc", "heap", "kernel"]

repository = "https://github.com/phil-opp/linked-list-allocator"
documentation = "http://phil-opp.github.io/linked-list-allocator/linked_list_allocator/index.html"
homepage = "http://os.phil-opp.com/kernel-heap.html#a-better-allocator"

exclude = [
    "scripts/*"
]
